### PR TITLE
[J3MK1] [ADD],[UPDATE] Documentation 07/30/2018

### LINKED ISSUE #69: Translate folder to EN-US:
eAmod/Documentations/Costumer/MD5 Hash Detection/

### PR DESCRIPTION
**Pull request by J3MK1**
- Translated file eAmod_Hash_Guide to EN-US.

- Translated file  eAmod_Mapflags to EN-US.

- Translated file eAmob-C_Rev-502-brAthena_Tests to EN-US.

Now, these files can be translated to ES and JP.

Closed #69.

### CODE REVIEW

**Comment by yufanee** [comment]
Good job J3MK1!!! I'm so happy to see your commitment!! 😄

**Comment by Zeferu** [comment]
When I recruited you and shellTeMP, I knew you would be hardworking and helpful, but I did not know you would be as willing as you have shown yourself! I'm proud to work with people like that.

**Comment by J3MK1** [comment]
Thank you @yufanee! ☺️✨

**Comment by J3MK1** [comment]
And thank you so much @Zeferu, It's a pleasure to be on eAmod team! 😭✨

**Pull request merged**
